### ISSUE TITLE
FindStringRef return nullptr

### ISSUE THREAD

**Issue by Extile00** [OutTheShade/UnrealMappingsDumper#11]
Hi!

I'm unsure if this is the right place for support.
I'm trying to generate mappings for a game demo (UE5.0.3) not an actual game. Is that even possible?
When running the .exe and injecting the dll, this is the error i get.
I can send the demo if need be. But i do not know how to write code myself.
My discord is Extile#3247

![error](https://user-images.githubusercontent.com/104039199/233862903-cd80612b-e177-4ab9-970f-1130a7465ffe.PNG)

**Comment by TheNaeem** [comment]
Fixed it and sent you the mappings. Enjoy!

**Comment by AnthorNet** [comment]
Having the same error on a 5.1 game, any hints on what was the problem as I don't see a commit related to the issue?

Thanks :)
