### ISSUE TITLE
Problem enjecting the dll into pubg 

### ISSUE THREAD

**Issue by Wackyhcky** [OutTheShade/UnrealMappingsDumper#14]
![image](https://github.com/OutTheShade/UnrealMappingsDumper/assets/45440717/cfe0b4fd-1c89-472b-8f5b-5e03fd1fac03)
This is the error i get when trying to inject the dll into pubg running unreal engine 4.16

**Comment by THW-Reaper** [comment]
Why would you need mappings for a 4.16 game?
