### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Oragani** [OutTheShade/UnrealMappingsDumper#15]
The game is running UE 5.0.3

Gives me a fatal error, here's the screenshot and the game
https://prnt.sc/WKDqsjg7Q5XW
https://drakelings.bluedrake42.com/index.php?/file/227-bodycam-prototype-level/

**Comment by TheNaeem** [comment]
Can you please try making the following change to this line in UnrealTypes.h and then let me know if works? 

(Add the highlighted line)
![image](https://github.com/OutTheShade/UnrealMappingsDumper/assets/84111816/68ce0411-3c30-4121-8809-6b6e88ec70b3)

**Comment by Oragani** [comment]
It worked, thank you for the help
