### ISSUE TITLE
Is there any requirements for DLL injection time? For example, before or after loading paks?

### ISSUE THREAD

**Issue by socialflower** [OutTheShade/UnrealMappingsDumper#18]
I packaged an empty project demo for UE5.0.3 with StartConent. After running the game with UnrealMappingsDumper.dll, I obtained the usmap file as follows.
[Mappings.zip](https://github.com/OutTheShade/UnrealMappingsDumper/files/12227451/Mappings.zip)
When exporting assets in FModel, I received an error message. It seems like there might be a problem with the usmap file, as it's only 96KB (.uasset has almost no information). How can I check if this usmap file is correct?
![image](https://github.com/OutTheShade/UnrealMappingsDumper/assets/34917146/cc460a03-1d2d-403f-8990-e55f15e3d1a7)
Here is the demo download url: https://drive.google.com/file/d/1wbCblBWx8biyRYavGdZ-bW_VWsG8vHYG/view?usp=sharing
Thanks!!!!

**Comment by socialflower** [comment]
Here is the demo download url: https://drive.google.com/file/d/1wbCblBWx8biyRYavGdZ-bW_VWsG8vHYG/view?usp=sharing
Thanks!!!!

**Comment by TheNaeem** [comment]
Sorry, I was on vacation the last couple of weeks. But yes, you must inject *after* the game has finished loading. Let me know if this helps at all. If it doesn't, then I'll take a look at the game myself sometime.

**Comment by socialflower** [comment]
Yesssss! I inject the dll after the game has finished loading, it works! Thank u very much!!!

**Comment by TheNaeem** [comment]
Glad to hear it works. Again, sorry for the late response. Enjoy!

**Comment by N4ok1** [comment]
im new to this so it might sound dumb but how do i inject the dll ;-;
