### ISSUE TITLE
Engine Ver. Detection

### ISSUE THREAD

**Issue by narknon** [OutTheShade/UnrealMappingsDumper#4]
Hello again,

I started implementing runtime UE version detection here: https://github.com/narknon/UnrealMappingsDumper/tree/VerFinder

I don't think I'll have time to finish though, and I realized that it will require refactoring some stuff so the sig scanning can occur earlier on in the initialization of the app, so I figure that would be better handled by you as I'm not sure how you'd prefer to refactor/adjust everything to do so.

**Comment by OutTheShade** [comment]
Thanks for the contribution! I'm kind of busy with school atm but I will take a look at implementing this when I can.
