### ISSUE TITLE
FF7 Support

### ISSUE THREAD

**Issue by speaker-60** [OutTheShade/UnrealMappingsDumper#5]
Im trying to use this with FF7r Intergrade
Nothing happens after loading the game and playing for a few minutes in a level, no usmap is generated

Im not sure what the best way is to inject the dll into the game, i tried using enb injector as you can tell it to inject any dll file
If there is a better way let me know so i can test with that

I can see this is more geared for fortnite focused, i did try v1.0.1 aswell

Is it a case that support for other games are not provided?
Im looking to convert umaps to jsons so i can use the data to rebuild the maps in blender
Fmodel cant read the umaps for ff7 and suggests a mapping file, hence im here

Any assistance would be appreciated

**Comment by narknon** [comment]
FF7R is a 4.18 game with unversioned header functionality ported into it by SQEX from UE 4.26.  It'll be pretty difficult to get this tool to support it due to the 7+ version difference from what it is intended for.  You can use the FF7R ps4 files and most tools will then work on them.

**Comment by narknon** [comment]
Do you have a discord or somewhere to DM you?

**Comment by narknon** [comment]
Here are some files that may help to add support.

[UE4SS_Signatures.zip](https://github.com/OutTheShade/UnrealMappingsDumper/files/9973220/UE4SS_Signatures.zip)

[Win64.zip](https://github.com/OutTheShade/UnrealMappingsDumper/files/9973216/Win64.zip)

#Set to 1 if you are manually defining GName, GObject, and GWorld by Patterns. Set to 0 if manually defining via offsets.
IsGInfoPatterns=0
GName=0x5934E80
GObject=0x53823C0
GWorld=0x590CAD8

**Comment by OutTheShade** [comment]
You're not accepting friend requests

**Comment by speaker-60** [comment]
Oh wow, wasnt expecting fast replies 

So yer i have the ps4 version all working, as that version is more straight forward
Even has a tool to recreate the maps https://forum.xentax.com/viewtopic.php?p=162674
Donst work with intergrade and the creator of the tool seems to have moved on and not supporting it or cant for the same reason of the multi versions issue maybe

Im after the additional maps in intergrade as im making an openworld midgar for fun as its what i have always wanted
Theres a lot of work to do with that but any and all maps i can get will help me

Thanks for taking an interest
my Discord BlueStar #7818

**Comment by TheNaeem** [comment]
I know this is late and I apologize, but thanks to @narknon a FF7 mappings is available https://github.com/OutTheShade/Unreal-Mappings-Archive/tree/main/CCFF7R
