### ISSUE TITLE
UE 5.1 Release support

### ISSUE THREAD

**Issue by Kein** [OutTheShade/UnrealMappingsDumper#9]
I'm getting a hard crash after injection and I'm unable to get any debug info because it seems to be inside engine code (that, or Visual Studio debugger being shit again).

**Comment by OutTheShade** [comment]
Compile it in debug mode and attach to your game. Inject the compiled DLL and send where it crashes and the call stack

**Comment by Kein** [comment]
That is what I did.

**Comment by OutTheShade** [comment]
Can you send it?

**Comment by Kein** [comment]
> I'm unable to get any debug info because it seems to be inside engine code (that, or Visual Studio debugger being shit again).

**Comment by OutTheShade** [comment]
You can still get the line it crashes on from the call stack. If you can't, just step through it line by line until it crashes and see where it happens

**Comment by Kein** [comment]
Nope, it simply does not work, it just segfaults without any break as if no debugger attached.
I managed to get a break in Rider, but its output is hard to read. Looks like it fails at
`DefaultEngine<T>::UObject::GetPathName(std::wstring& Result, UObject* StopOuter)` in `engine.cpp`:41:
`Result += NamePrivate.AsString();`
ComparisonIndex and Number seem valid for FName: 117768197 and 87832
The final crash is inside Engine code:
![image](https://user-images.githubusercontent.com/623756/203178975-da2359e2-e0c1-4433-8b43-2f4f1b22df55.png)

**Comment by OutTheShade** [comment]
What game is this for?

**Comment by Kein** [comment]
No game, 5.1 vanilla build, I've just compiled UnrealGame target

**Comment by OutTheShade** [comment]
I'm currently on vacation so I can't do much to help but the problem is very likely to be the patterns of GObjects and/or FNameToString

I recommend reversing them yourself if you can, and override the addresses. Unfortunately someone pushed some faulty patterns for them recently and that commit will be reverted soon

**Comment by Kein** [comment]
If `FNameToString` is invalid pattern then how come it ended up in UE's `FName::ToString` in the end?
What do you mean by `reversing`.

**Comment by OutTheShade** [comment]
There's nothing to indicate that it ended up in UE's fnametostring. If you look at the code of the dumper it calls the function pointer which points to what should be fnametostring, but if it isn't fnametostring it would be invalid 

And if you don't know what I mean by reversing then don't worry about it. Like I said I'm not gonna be home for like another week but if you send a link to download the exe of ur game, I can see what I can do

**Comment by Kein** [comment]
> There's nothing to indicate that it ended up in UE's fnametostring.
What do you mean there is nothing? Callstack? 
```
FName::ToString() UnrealNames.cpp:3371
FNameBase::AsString() engine.cpp:9
```
if this does not indicate FNAME:ToString pattern was correct then what else?
Which patterns the tool is looking for? Where they are defined?

**Comment by Kein** [comment]
>  that's the FNameToString wrapper in my code. It just calls UE's FNameToString, but we don't know that it actually did fall UE's FNameToString
???
Literally in my callstack posted above where break is being triggered inside Engine code:
`[Inlined] FName::ToString(FString &) UnrealNames.cpp:3399`

**Comment by OutTheShade** [comment]
Can you provide a link to download the games exe. The problem is likely GObjects

**Comment by Kein** [comment]
https://www58.zippyshare.com/v/vL7TE779/file.html

**Comment by OutTheShade** [comment]
Thanks. I'll have a look at it when I can but no guarantees it will be quick, I'm pretty busy.
